apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: $ECR_REPO:latest
        ports:
        - containerPort: 3001
        env:
          - name: PORT
            value: "3001"
          - name: NODE_ENV
            value: "development"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: cart-service-secrets
                key: database-url
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: cart-service-secrets
                key: s3-bucket
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: cart-service-secrets
                key: aws-region
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: cart-service