apiVersion: v1
kind: Secret
metadata:
  name: cart-service-secrets
type: Opaque
stringData:
  database-url: "postgresql://postgres:admin12345@mydb2.cfwsoy60i9bt.us-east-2.rds.amazonaws.com:5432/ecomm"
  s3-bucket: "ecommerce-bucket-kube2"
  aws-region: "us-east-2"
  apiUrl: "http://a58f74e828e3f4d199f1ca6e52cdda85-1243110776.us-east-2.elb.amazonaws.com/"
  