apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        # Use the full ECR URL with the dynamic image tag
        image: 195275674076.dkr.ecr.us-east-2.amazonaws.com/react-app-repo:33
        imagePullPolicy: Always  # Ensure Kubernetes always pulls the latest image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: react-app
